# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Wng7YMYlUYLGCjipq6_IEPHmAb37fN-
"""

!pip install mlflow pyngrok -q

!python modelling.py

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

try:
    df = pd.read_csv("water_potability_preprocessing.csv")
except:
    df = pd.read_csv("/content/water_potability_preprocessing.csv")

X = df.drop("Potability", axis=1)
y = df["Potability"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

mlflow.set_experiment("Eksperimen_Air_Layak_Minum__Derryl_Priyambodo")
mlflow.sklearn.autolog()

with mlflow.start_run():
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    acc = accuracy_score(y_test, model.predict(X_test))
    print(f"Model trained with Accuracy: {acc}")

import os
import time
import requests
from pyngrok import ngrok

NGROK_TOKEN = "379fb0CdP9GPawS9Ha2Yc1q1RBc_7jihBbwNqhBK4ZBTfBcEo"

ngrok.set_auth_token(NGROK_TOKEN)

print("Membersihkan proses lama...")
get_ipython().system_raw("pkill mlflow")
get_ipython().system_raw("pkill ngrok")

print("Menjalankan MLflow...")
get_ipython().system_raw("mlflow ui --host 0.0.0.0 --port 5000 &")

ngrok_path = ngrok.conf.get_default().ngrok_path
cmd = f"{ngrok_path} http 5000 --host-header='localhost:5000' > /dev/null 2>&1 &"
os.system(cmd)

print("Menunggu koneksi Ngrok stabil (3 detik)...")
time.sleep(3)

try:
    response = requests.get("http://localhost:4040/api/tunnels")
    tunnels = response.json()['tunnels']

    public_url = tunnels[0]['public_url']

    print("\n" + "="*50)
    print(f"KLIK LINK INI UNTUK DASHBOARD: {public_url}")
    print("="*50)
    print("Jangan lupa screenshot dashboardnya untuk tugas!")

except Exception as e:
    print("\nGagal mendapatkan URL.")
    print("Pastikan Token Ngrok sudah benar dan kamu tidak menjalankan sel ini berkali-kali terlalu cepat.")
    print(f"Error detail: {e}")